[tool.poetry]
name = "git-portfolio"
version = "0.1.0"
description = "Manage all your Git repositories, organisations, providers from one place."
authors = ["Vikash Kothary <kothary.vikash@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
PyGithub = "^1.45"
python-gitlab = "^2.0.0"
gitpython = "^3.0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
