#!/usr/bin/env bash
# file: poetry-export.sh
# description: Lock dependencies and export requirements.

echo "# file: requirements.txt" > src/requirements.txt
echo "# description: Dependencies generated by Poetry. DO NOT EDIT DIRECTLY!" >> src/requirements.txt
printf "# date: $(date '+%Y-%m-%d')\n\n" >> src/requirements.txt

echo "# file: requirements-dev.txt " > src/requirements-dev.txt
echo "# description: Dev dependencies generated by Poetry DO NOT EDIT DIRECTLY!" >> src/requirements-dev.txt
printf "# date: $(date '+%Y-%m-%d')\n\n" >> src/requirements-dev.txt

# Lock Poetry dependencies
poetry lock

# Generate requirement files for backward compatibility.
poetry export --without-hashes -f requirements.txt >> src/requirements.txt
poetry export --dev --without-hashes -f requirements.txt >> src/requirements-dev.txt

# Include editable install for src
echo "-e src/." >> src/requirements-dev.txt


