strict: true
theme: readthedocs
site_name: Git Portfolio
site_description: Manage all your Git repositories, organisations, providers from one place.
site_author: Vikash Kothary
site_url: https://vikash-kothary.github.io/git-portfolio
repo_url: https://github.com/vikash-kothary/git-portfolio
docs_dir: src
site_dir: build